// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthHealthCheckResponse, UploadUploadZipData, UploadUploadZipResponse } from './types.gen';

export class HealthService {
    /**
     * Health Check
     * Secured health check endpoint.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthHealthCheck(): CancelablePromise<HealthHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health/health',
            errors: {
                404: 'Not found'
            }
        });
    }
    
}

export class UploadService {
    /**
     * Upload Zip
     * Secure endpoint to upload and process zip files, ensuring valid JWTs.
     * @param data The data for the request.
     * @param data.formData
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static uploadUploadZip(data: UploadUploadZipData): CancelablePromise<UploadUploadZipResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/upload/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                404: 'Not found',
                422: 'Validation Error'
            }
        });
    }
    
}